# Generated by Django 4.2.10 on 2024-02-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="expression",
            field=models.TextField(),
        ),
    ]
