# Generated by Django 4.2.10 on 2024-02-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_alter_rule_expression"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="reason",
            field=models.TextField(),
        ),
    ]
