# Generated by Django 4.2.10 on 2024-02-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_questionnaire_order_items_alter_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="slug",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
