# Generated by Django 4.2.10 on 2024-02-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_questionnaire_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="questions",
            field=models.ManyToManyField(to="orders.questionnaire"),
        ),
    ]
