# Generated by Django 4.2.10 on 2024-02-23 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_product_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.product"
            ),
        ),
        migrations.AlterField(
            model_name="orderquestionnaire",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_questions",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderquestionnaire",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="orders.questionnaire",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="question",
            field=models.TextField(max_length=255),
        ),
    ]
